# Generated by Django 5.2.6 on 2026-10-04 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_commercial_priority_product_match_keywords_and_more"),
        ("prospecting", "0002_territory_prospect_territory"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("score", models.PositiveSmallIntegerField(default=0)),
                ("score_version", models.CharField(default="rules-v1", max_length=20)),
                ("explanation", models.TextField(max_length=1000)),
                ("score_breakdown", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("ACCEPTED", "Aceptada"),
                            ("POSTPONED", "Postergada"),
                            ("DISCARDED", "Descartada"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("review_reason", models.CharField(blank=True, max_length=500)),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="catalog.product",
                    ),
                ),
                (
                    "prospect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="prospecting.prospect",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-score", "prospect__name", "product__name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "status", "score"],
                        name="opportunity_tenant_status_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "prospect", "product"),
                        name="unique_opportunity_per_tenant_prospect_product",
                    )
                ],
            },
        ),
    ]
