# Generated by Django 5.2.6 on 2026-10-04 19:56

from django.db import migrations, models
import unicodedata


VALID_CODES = {
    "FOOD_SERVICE", "HOSPITALITY", "RETAIL", "WHOLESALE", "FOOD_PRODUCTION",
    "HEALTHCARE", "EDUCATION", "CONSTRUCTION", "LOGISTICS", "MANUFACTURING",
    "PROFESSIONAL_SERVICES", "OTHER",
}


def canonical_industry(value):
    if not value:
        return ""
    if value in VALID_CODES:
        return value
    normalized = "".join(
        character for character in unicodedata.normalize("NFKD", value.casefold())
        if not unicodedata.combining(character)
    )
    rules = (
        (("restaurant", "restobar", "cafeter", "gastronom"), "FOOD_SERVICE"),
        (("hotel", "hostal", "alojamiento"), "HOSPITALITY"),
        (("mayorista", "distribu"), "WHOLESALE"),
        (("retail", "minorista", "tienda", "comercio"), "RETAIL"),
        (("alimento", "panader", "elaboracion"), "FOOD_PRODUCTION"),
        (("salud", "clinica", "hospital"), "HEALTHCARE"),
        (("educ", "colegio", "universidad"), "EDUCATION"),
        (("construc", "inmobil", "ferreter"), "CONSTRUCTION"),
        (("transport", "logistic"), "LOGISTICS"),
        (("manufact", "fabrica"), "MANUFACTURING"),
        (("profesional", "consultor", "asesor"), "PROFESSIONAL_SERVICES"),
    )
    for terms, code in rules:
        if any(term in normalized for term in terms):
            return code
    return "OTHER"


def normalize_existing_industries(apps, schema_editor):
    Prospect = apps.get_model("prospecting", "Prospect")
    Product = apps.get_model("catalog", "Product")
    for prospect in Prospect.objects.exclude(industry="").iterator():
        prospect.industry = canonical_industry(prospect.industry)
        prospect.save(update_fields=["industry"])
    for product in Product.objects.iterator():
        normalized = list(dict.fromkeys(canonical_industry(value) for value in product.target_industries if value))
        if normalized != product.target_industries:
            product.target_industries = normalized
            product.save(update_fields=["target_industries"])


class Migration(migrations.Migration):

    dependencies = [
        ("prospecting", "0003_opportunity"),
    ]

    operations = [
        migrations.RunPython(normalize_existing_industries, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="prospect",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FOOD_SERVICE", "Restaurantes, restobares y cafeterías"),
                    ("HOSPITALITY", "Hoteles y alojamientos"),
                    ("RETAIL", "Comercio minorista"),
                    ("WHOLESALE", "Distribución y comercio mayorista"),
                    ("FOOD_PRODUCTION", "Producción y elaboración de alimentos"),
                    ("HEALTHCARE", "Salud y cuidado"),
                    ("EDUCATION", "Educación"),
                    ("CONSTRUCTION", "Construcción e inmobiliario"),
                    ("LOGISTICS", "Transporte y logística"),
                    ("MANUFACTURING", "Manufactura"),
                    ("PROFESSIONAL_SERVICES", "Servicios profesionales"),
                    ("OTHER", "Otros"),
                ],
                max_length=32,
            ),
        ),
    ]
