# Generated by Django 5.2.6 on 2026-10-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="commercial_priority",
            field=models.CharField(
                choices=[("LOW", "Baja"), ("MEDIUM", "Media"), ("HIGH", "Alta")],
                default="MEDIUM",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="match_keywords",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="product",
            name="target_industries",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
