# Generated by Django 5.2.6 on 2026-09-23 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("tenancy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuoteRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=160)),
                ("company_name", models.CharField(blank=True, max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("message", models.TextField(blank=True, max_length=1500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "Nueva"),
                            ("CONTACTED", "Contactada"),
                            ("CLOSED", "Cerrada"),
                        ],
                        default="NEW",
                        max_length=12,
                    ),
                ),
                ("consent_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quote_requests",
                        to="tenancy.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuoteRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=160)),
                ("product_sku", models.CharField(max_length=80)),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quote_request_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "quote_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="inquiries.quoterequest",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="quoterequest",
            index=models.Index(
                fields=["tenant", "status", "-created_at"],
                name="inquiry_tenant_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="quoterequestitem",
            constraint=models.UniqueConstraint(
                fields=("quote_request", "product"),
                name="unique_product_per_quote_request",
            ),
        ),
    ]
